networks:
  lan:

services:
  pinguino-cc:
    build: .
    container_name: pinguino-cc
    working_dir: /app
    command: ["yarn", "start", "--host", "0.0.0.0", "--port", "5173"]
    networks:
      - lan
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
