name: docs-dev

on: workflow_dispatch
  # trigger deployment on every push to main branch
  #push:
    #branches-ignore: [master]
  # trigger deployment manually

jobs:
  docs-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This version of Vitepress need node v12
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install

      # run build script
      - name: Build VitePress site
        run: yarn build
        env:
          VITEPRESS_BASE: /pinguinoide.github.io/

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VitePress
          build_dir: site/.vitepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
